[package]
name = "rust_blinky2"
version = "0.1.0"
edition = "2021"

[dependencies]
rp2040-hal = "0.7.0"
embedded-hal = { version = "0.2.5", features = ["unproven"] }
rp2040-boot2 = "0.3.0"
panic-halt = "1.0.0"
cortex-m-rt = "0.7.3"
cortex-m = "0.7.7"
